apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
# NOTE: so this is possible
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"

reclaimPolicy: Retain
allowVolumeExpansion: true

parameters:
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io

# TODO: this is useless
#allowedTopologies:
#- matchLabelExpressions:
#  - key: kubernetes.io/hostname
#    values:
#      - smol
